export const CONSTANTS = {
    FETCH_TODOLIST: {
        REQUEST: 'FETCH_TODOLIST_REQUEST',
        SUCCEED: 'FETCH_TODOLIST_SUCCEED',
        FAILED: 'FETCH_TODOLIST_FAILED'
    },
    ADD_TODO: {
        REQUEST: 'ADD_TODO_REQUEST',
        SUCCEED: 'ADD_TODO_SUCCEED',
        FAILED: 'ADD_TODO_FAILED'
    },
    DELETE_TODO: {
        REQUEST: 'DELETE_TODO_REQUEST',
        SUCCEED: 'DELETE_TODO_SUCCEED',
        FAILED: 'DELETE_TODO_FAILED'
    },
    TOGGLE_TODO: {
        REQUEST: 'TOGGLE_TODO_REQUEST',
        SUCCEED: 'TOGGLE_TODO_SUCCEED',
        FAILED: 'TOGGLE_TODO_FAILED'
    }
}